# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
    #    AppBundle\Entity\Trainee: plaintext
      Symfony\Component\Security\Core\User\User: plaintext
      AppBundle\Entity\User: plaintext
    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER]
    providers:
      chain_provider:
        chain:
          providers: [in_memory, db]
      in_memory:
        memory:
          users:
            admin: { password : abcd123 , roles: 'ROLE_ADMIN'}
      db:
        entity:
          class: AppBundle:User
          property: email

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            anonymous: ~
            provider: chain_provider
            form_login:
              login_path: login
              check_path: login
              default_target_path: userProfile
            logout:
              path: logout
              target: login
            security: true
            anonymous: true
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
    access_control:
      - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/test, roles: ROLE_ADMIN }
      - { path: ^/newCompartment, roles: ROLE_USER }
      - { path: ^/editCompartment, roles: ROLE_USER }